apiVersion: cnsl.dev.cnsl.krsiepolicy.com/v1alpha1
kind: KrsiePolicy
metadata:
  name: krsiepolicy-tor
spec:
  message: "Deny known torproxy ports"
  selector:
    matchLabels: 
      group: torproxy-group
  syscall: socket_listen
  lsmHook: socket_listen
  conditions:
    - parameter: data.local_port
      operator:
        ==
      value: "9050"
      action: 
        Deny