apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-for-krsie
rules:
- apiGroups: ["cnsl.dev.cnsl.krsiepolicy.com", ""]
  resources: ["pods", "nodes", "krsiepolicies"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-for-krsie-rbac
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: admin-for-krsie
  apiGroup: rbac.authorization.k8s.io